services:
  proxy:
    ports: !override ["127.0.0.1:8088:8088"]
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile:ro

  web:
    environment:
      DEPLOYMENT_ENV: staging

  mailpit:
    image: axllent/mailpit@sha256:81370195cd4a0eab9604d17c2617a7525b0486f9365555253b6c5376c6350f1a
    logging:
      driver: json-file
      options: {max-size: 10m, max-file: "3"}
    restart: unless-stopped
    ports: ["127.0.0.1:8025:8025"]
    networks: [backend]
    mem_limit: 128m
